name: CI

on: [push, pull_request]

jobs:
    test:
        name: Node.js v${{ matrix.nodejs }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                nodejs: [14]

        steps:
            -   uses: actions/checkout@master
                with:
                    fetch-depth: 1

            -   uses: actions/setup-node@v1
                with:
                    node-version: ${{ matrix.nodejs }}

            -   name: Install
                run: |
                    yarn global add c8 rimraf rollup
                    yarn install

            -   name: Test
                run: yarn test:coverage

            -   name: Report
                if: matrix.nodejs >= 14
                run: |
                    yarn test:report
                    bash <(curl -s https://codecov.io/bash)
                env:
                    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
